version: "3.7"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./src:/src
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - nginx
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/src
    working_dir: /src
    networks:
      default:
        aliases:
          - php
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - db
networks:
  default:
